source 'https://rubygems.org'

# gem "github-pages"#, '>=197'#, group: :jekyll_plugins

group :jekyll_plugins do
    gem 'jekyll-relative-links'
    # gem 'jekyll-sitemap'
    gem 'jekyll-paginate'
end